"""Initial migration.

Revision ID: 215713663c09
Revises: 736f24ec0d43
Create Date: 2020-02-01 00:31:26.724034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215713663c09'
down_revision = '736f24ec0d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video__game__achievements', sa.Column('video_game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'video__game__achievements', 'video__game', ['video_game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video__game__achievements', type_='foreignkey')
    op.drop_column('video__game__achievements', 'video_game_id')
    # ### end Alembic commands ###
