"""empty message

Revision ID: 440d89a92045
Revises: fc88da9345b6
Create Date: 2020-02-02 13:59:59.569777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440d89a92045'
down_revision = 'fc88da9345b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('lore_link', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_game')
    # ### end Alembic commands ###
