"""empty message

Revision ID: 4dc28bfcce67
Revises: 43e0eea3e1da
Create Date: 2020-02-02 13:52:39.921365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc28bfcce67'
down_revision = '43e0eea3e1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_game', 'lore_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_game', sa.Column('lore_link', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
