"""Initial migration.

Revision ID: 736f24ec0d43
Revises: 37bdfec7f8af
Create Date: 2020-02-01 00:25:12.738691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736f24ec0d43'
down_revision = '37bdfec7f8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video__game__achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video__game__achievements')
    # ### end Alembic commands ###
