"""empty message

Revision ID: aa4335c154b2
Revises: bb20f50dc6ce
Create Date: 2020-02-01 14:58:01.449601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4335c154b2'
down_revision = 'bb20f50dc6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_world_game_towg_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('entry_title', sa.String(length=100), nullable=False),
    sa.Column('entry_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_world_game_towg_journal')
    # ### end Alembic commands ###
