"""empty message

Revision ID: d52b1917310a
Revises: da762710683f
Create Date: 2020-02-01 01:07:06.703214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52b1917310a'
down_revision = 'da762710683f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_game_achievements', sa.Column('video_game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'video_game_achievements', 'video_game', ['video_game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_game_achievements', type_='foreignkey')
    op.drop_column('video_game_achievements', 'video_game_id')
    # ### end Alembic commands ###
