"""empty message

Revision ID: f3c356822cc4
Revises: d52b1917310a
Create Date: 2020-02-01 01:08:46.281948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c356822cc4'
down_revision = 'd52b1917310a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_game_achievements', sa.Column('video_game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video_game_achievements', 'video_game', ['video_game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_game_achievements', type_='foreignkey')
    op.drop_column('video_game_achievements', 'video_game_id')
    # ### end Alembic commands ###
